{% set name = "sceptre-file-resolver" %}
{% set version = "1.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sceptre-file-resolver-{{ version }}.tar.gz
  sha256: d47cfe32d141fb46467fcd319bf4386f0178cf0c2211c6f1d2dffbc80d785a6d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=3
    - python >=3.6
  run:
    - packaging ==16.8
    - python >=3.6
    - requests >=2.25,<3

test:
  imports:
    - resolver
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sceptre/sceptre-file-resolver
  summary: A Sceptre resolver to retrieve file content
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - admax18
    - mxr-conda
